---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-dev
  namespace: dev
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/dev
  prune: true
  wait: true
  timeout: 5m0s
  # patches:
  #   - patch: |
  #       - op: replace
  #         path: /spec/acme/server
  #         value: https://acme-v02.api.letsencrypt.org/directory
  #     target:
  #       kind: HelmRelease
  #       name: postgresql
