---
apiVersion: v1
kind: Namespace
metadata:
  name: objectstore
  labels:
    toolkit.fluxcd.io/tenant: dbs
    istio-injection: disabled
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: objectstore
  namespace: flux-system
spec:
  targetNamespace: objectstore
  interval: 10m0s
  # dependsOn:
  #   - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/base/objectstore
  prune: true
  wait: true
  timeout: 5m0s
  # patches:
  #   - patch: |
  #       - op: replace
  #         path: /metadata/namespace
  #         value: dev
  #     target:
  #       kind: HelmRelease
  #       name: postgresql
