---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: chromadb
  namespace: dev
spec:
  hosts:
  - chromadb.k8s
  gateways:
  - istio-ingress/k8s-gateway
  - mesh # applies to all the sidecars in the mesh
  http:
  - route:
    - destination:
        host: chromadb.dev.svc.cluster.local
        port:
          number: 8000
