---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
spec:
  releaseName: mysql
  chart:
    spec:
      chart: mysql
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bitnami
  interval: 50m
  install:
    remediation:
      retries: 3
  values: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: phpmyadmin
spec:
  releaseName: phpmyadmin
  timeout: 10m
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: phpmyadmin
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bitnami
  interval: 50m
  values: {}
