---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    toolkit.fluxcd.io/tenant: dbs
    istio-injection: disabled
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 24h
  ref:
    branch: main
  url: https://github.com/cert-manager/cert-manager.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-crds
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./deploy/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: cert-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: jetstack
  interval: 50m
  values: {}
