---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    toolkit.fluxcd.io/tenant: ingress
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 60m
  url: https://istio-release.storage.googleapis.com/charts
---
# helm upgrade -i istio-base istio/base -n istio-system
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  releaseName: istio-base
  interval: 60m
  chart:
    spec:
      chart: base
      version: "1.23.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 12h
  values: {}
---
# helm upgrade -i istiod istio/istiod -n istio-system --wait -f /tmp/istio-values.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  releaseName: istiod
  interval: 60m
  chart:
    spec:
      chart: istiod
      version: "1.23.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 12h
  values: {}
    # meshConfig:
    #   extensionProviders: # The following content defines two example tracing providers.
    #   - name: "localtrace"
    #     zipkin:
    #       service: "jaeger-collector.jaeger.svc.cluster.local"
    #       port: 9411
    #       maxTagLength: 56
