---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak-operator
  labels:
    toolkit.fluxcd.io/tenant: auth
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak-operator
  namespace: keycloak-operator
spec:
  releaseName: keycloak-operator
  chart:
    spec:
      chart: keycloak-operator
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: epamedp
  interval: 50m
  install:
    remediation:
      retries: 3
  values: {}
