apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: home-assistant
spec:
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: postgresql
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    auth:
      username: home
      database: homeassistant
      existingSecret: pg-access
      secretKeys:
        adminPasswordKey: admin
        userPasswordKey: user
        replicationPasswordKey: replication
