---
apiVersion: v1
kind: Secret
metadata:
  name:  keycloak-user-log4ham
type: Opaque
data:
  password: YmVu # base64-encoded value of "ben"
---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmUser
metadata:
  name: master-user-log4ham
spec:
  realmRef:
    name: master
    kind: KeycloakRealm
  username: ben
  firstName: "Ben"
  lastName: "Greene"
  email: "ben.greene@example.com"
  enabled: true
  emailVerified: true
  keepResource: true
  roles:
    - offline_access
  groups:
    - Readers
  attributes:
    foo: "bar"
    baz: "jazz"
  passwordSecret:
    name: keycloak-user-ben
    key: password
