---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
spec:
  releaseName: keycloak
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bitnami
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    image:
      tag: 26-debian-12
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        labels:
          release: prometheus-stack
    httpRelativePath: /auth/
    postgresql:
      enabled: false
    externalDatabase:
      host: postgresql-postgresql-ha-pgpool.dbs.svc.cluster.local
      user: security-pg-keycloak
      database: security-pg-keycloak
      port: 5432
      existingSecret: keycloak-postgresql
