apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: mining
resources:
  - ./namespace.yaml
  - ../base/xmrig
patches:
  - patch: |
      - op: add
        path: /metadata/namespace
        value: mining
      - op: replace
        path: /metadata/namespace
        value: mining
    target:
      kind: HelmRelease
