---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    toolkit.fluxcd.io/tenant: ingress
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 60m
  url: https://istio-release.storage.googleapis.com/charts
---
# helm upgrade -i istio-base istio/base -n istio-system
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  releaseName: istio-base
  interval: 60m
  chart:
    spec:
      chart: base
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 12h
  values: {}
