---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
  labels:
    toolkit.fluxcd.io/tenant: ingress
---
# helm upgrade -i istio-ingress istio/gateway -n istio-ingress --wait
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  releaseName: gateway
  interval: 60m
  chart:
    spec:
      chart: gateway
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 12h
  values: {}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
  namespace: istio-ingress
spec:
  selector:
    app: istio-ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.k8s"
