apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - cert-manager.yaml
  # - ingress-nginx.yaml
  # - weave-gitops.yaml
  - istio-system.yaml
  - istio-ingress.yaml
  - metallb-system.yaml
