apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata: [ originAnnotations ]
resources:
  # - ../base/podinfo
  # - ../base/home-assistant
  - ../base/minio
patches: []
  # - path: podinfo-values.yaml
  #   target:
  #     kind: HelmRelease
