---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 69m
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: polecatworks
  namespace: flux-system
spec:
  interval: 60m
  type: oci
  url: oci://ghcr.io/polecatworks
  secretRef:
    name: helm-ghcr-io
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: runix
  namespace: flux-system
spec:
  interval: 69m
  url: https://helm.runix.net
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: epamedp
  namespace: flux-system
spec:
  interval: 69m
  url: https://epam.github.io/edp-helm-charts/stable
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 60m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: db-operator
  namespace: flux-system
spec:
  interval: 60m
  url: https://db-operator.github.io/charts
