---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
spec:
  releaseName: keycloak
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bitnami
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    httpRelativePath: /auth/
