apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: dev
resources:
  - ./namespace.yaml
  - ./pg-secrets.yaml
  - ./virtualservice.yaml
  - ../base/postgresql
  - ../base/minio
patches:
  - patch: |
      - op: replace
        path: /metadata/namespace
        value: dev
    target:
      kind: HelmRepository
  - patch: |
      - op: replace
        path: /metadata/namespace
        value: dev
    target:
      kind: HelmRelease
      name: postgresql
  - patch: |
      - op: replace
        path: /metadata/namespace
        value: dev
    target:
      kind: HelmRelease
      name: minio
