apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ../base/postgresql
  # # - ../base/home-assistant
  # - ../base/minio
patches:
  - patch: |
      - op: replace
        path: /metadata/namespace
        value: dev
    target:
      kind: HelmRelease
      name: postgresql
