apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: dev
resources:
  - ./namespace.yaml
  - ./monitoring.yaml
  - ./pg-secrets.yaml
  - ./virtualservice.yaml
  # - ../base/chroma
  - ../base/postgresql
  - ../base/helm-repos
  - ../base/k8s-python
  # - ../base/milvus
  # - ../base/minio
patches:
  - patch: |
      - op: add
        path: /metadata/namespace
        value: dev
      - op: replace
        path: /metadata/namespace
        value: dev
    target:
      kind: HelmRelease
  # # Does not work as needs Bitnami image: Suggestion here to solve https://github.com/bitnami/containers/issues/32677
  - patch: |
      - op: add
        path: /spec/values/image
        value:
          registry: ghcr.io
          repository: polecatworks/postgresql-vector
          tag: main
          pullSecrets:
            - name: dockerconfigjson-ghcr-io
      - op: add
        path: /spec/values/global
        value:
          security:
            allowInsecureImages: true
    target:
      kind: HelmRelease
      name: postgresql
