---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    toolkit.fluxcd.io/tenant: dev
    istio-injection: enabled
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: ns-default
  namespace: dev
spec:
  accessLogging:
    - providers:
      - name: envoy
