---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: dev-k8s
  namespace: dev
spec:
  hosts:
  - dev.k8s
  gateways:
  - istio-ingress/k8s-gateway
  - mesh # applies to all the sidecars in the mesh
  http:
  - name: k8s-python
    match:
      - uri:
          prefix: /k8s-python
    route:
    - destination:
        host: k8s-python
        port:
          number: 80
