---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: dev-k8s
  namespace: dev
spec:
  hosts:
  - dev.k8s
  gateways:
  - istio-ingress/k8s-gateway
  - mesh # applies to all the sidecars in the mesh
  http:
  - name: pie-k8s-python
    match:
      - uri:
          prefix: /pie/v0/
    route:
    - destination:
        host: pie-k8s-python
        port:
          number: 80
  - name: cake-k8s-python
    match:
      - uri:
          prefix: /cake/v0/
    route:
    - destination:
        host: cake-k8s-python
        port:
          number: 80
  - name: ui-shell
    match:
      - uri:
          prefix: /
    route:
    - destination:
        host: ui-shell-nginx-view
        port:
          number: 80
