---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
spec:
  releaseName: minio
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: minio
  interval: 50m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    replicas: 3
    persistence:
      size: 10Gi
      storageClass: longhorn-single

    resources:
      requests:
        memory: 1Gi
    metrics:
      serviceMonitor:
        enabled: true
        # Modifying release is not allowed as it is a reserved label (by Minio Chart)
        # additionalLabels:
        #   release: prometheus-stack
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: ServiceMonitor
            patch: |
              - op: replace
                path: /metadata/labels/release
                value: prometheus-stack
