apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  releaseName: home-assistant
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  interval: 50m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    env:
      TZ: Europe/Belfast
    # postgresql:
    #   enabled: true
    http:
      server_host: 0.0.0.0
      ip_ban_enabled: false
      login_attempts_threshold: 5
      use_x_forwarded_for: true
    controller:
      volumes:
        cache-volume:
          persistant: true
          type: emptyDir
          medium: Memory
          sizeLimit: 50Mi
