apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  releaseName: home-assistant
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  interval: 50m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    env:
      TZ: Europe/Belfast
    # postgresql:
    #   enabled: true
    initContainers:
      init-config:
        volumeMounts:
        - mountPath: /config_overrides
          name: config_overrides
        - mountPath: /shared
          name: shared
        command:
        - /config_overrides/configcopy.sh
        #  ["/bin/sh", "-c"]
        # args:
        # - echo starting;
        #   ls -la /backups;
        #   mysqldump --host=... -r /backups/file.sql db_name;
        #   ls -la /backups;
        #   echo done;
    persistence:
      # configload:
      #   enabled: true
      #   type: configMap
      #   name: "{{ .Release.Name }}-ha-config"
      #   mountPath: /config/configuration.yaml
      #   subPath: configuration.yaml
      #   readOnly: true
      shared:
        enabled: true
      config_overrides:
        enabled: true
        type: configMap
        name: "{{ .Release.Name }}-config-overrides"
    configmap:
      config-overrides:
        enabled: true
        data:
          configcopy.sh: |
            #!/bin/bash
            echo Start copy here
            ls /shared
            ls /config
            ls /config_overrides

            echo Copy complete
          configuration.yaml: |
            ---
            # Loads default set of integrations. Do not remove.
            default_config:
            http:
              server_host: 0.0.0.0
              ip_ban_enabled: false
              login_attempts_threshold: 5
              use_x_forwarded_for: true
            # Text to speech
            tts:
              - platform: google_translate

            automation: !include automations.yaml
            script: !include scripts.yaml
            scene: !include scenes.yaml
          # automations.yaml: |
          #   ---
          #   []
          # scripts.yaml: |
          #   ---
          # scenes.yaml: |
          #   ---
          # secrets: |
          #   ---
          #   # Use this file to store secrets like usernames and passwords.
          #   # Learn more at https://www.home-assistant.io/docs/configuration/secrets/
          #   some_password: welcome
