---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: k8s-at-home
  namespace: home-assistant
spec:
  interval: 5m
  url: https://k8s-at-home.com/charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgresql
  namespace: home-assistant
spec:
  interval: 5m
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
