---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql-ha
spec:
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql-ha
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bitnami
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    postgresql:
      existingSecret: pg-access
  # values:
  #   auth:
  #     username: myuser
  #     database: mydb
  #     existingSecret: pg-access
  #     secretKeys:
  #       adminPasswordKey: admin
  #       userPasswordKey: user
  #       replicationPasswordKey: replication
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin4
spec:
  releaseName: pgadmin
  chart:
    spec:
      chart: pgadmin4
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: runix
  interval: 50m
  values:
    existingSecret: pgadmin4-password
    env:
      # can be email or nickname
      email: admin@admin.com
