---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgresql
  namespace: flux-system
spec:
  interval: 69m
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: runix
  namespace: flux-system
spec:
  interval: 69m
  url: https://helm.runix.net
