---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        namespace: prometheus
        name: prometheus-community
  interval: 50m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values: {}
