---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-stack
spec:
  releaseName: prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: prometheus-community
  interval: 50m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    prometheus:
      prometheusSpec:
        serviceMonitorSelector:
          matchLabels:
            release: prometheus-stack
          # matchExpressions:
          # - { key: release, operator: In, values: [prometheus-stack] }
          # - { key: monitor, operator: In, values: [prometheus-stack] }
