---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig
  namespace: mining
  labels:
    app: xmrig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      containers:
      - name: xmrig
        image: ghcr.io/murf2/xmrig.docker:6.20.0
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 5000Mi
            cpu: 1500m
        env:
        - name: POOL_PASS
          # Worker ID
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: mining0
              # Specify the key associated with the value
              key: POOL_PASS
        - name: POOL_URL
          # Pool URL
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: mining0
              # Specify the key associated with the value
              key: POOL_URL
        - name: POOL_USER
          # Wallet ID
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: mining0
              # Specify the key associated with the value
              key: POOL_USER
