---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig
  namespace: mining
  labels:
    app: xmrig
spec:
  replicas: 5
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - xmrig
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: xmrig
        image: ghcr.io/murf2/xmrig.docker:6.20.0
        ports:
        # - containerPort: 80
        resources:
          requests:
            # memory: 5000Mi
            cpu: 2000m
          # limits:
          #   # memory: 5000Mi
          #   cpu: 3500m
        env:
        - name: POOL_PASS
          # Worker ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
          # valueFrom:
          #   configMapKeyRef:
          #     # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
          #     name: mining0
          #     # Specify the key associated with the value
          #     key: POOL_PASS
        - name: POOL_URL
          # Pool URL
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: mining0
              # Specify the key associated with the value
              key: POOL_URL
        - name: POOL_USER
          # Wallet ID
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: mining0
              # Specify the key associated with the value
              key: POOL_USER
        - name: THREADS
          # Wallet ID
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: mining0
              # Specify the key associated with the value
              key: THREADS
