---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: milvus
spec:
  releaseName: milvus
  chart:
    spec:
      chart: milvus
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bitnami
  interval: 50m
  install:
    remediation:
      retries: 3
  values: {}
    # auth:
    #   username: myuser
    #   database: mydb
    #   existingSecret: pg-access
    #   secretKeys:
    #     adminPasswordKey: admin
    #     userPasswordKey: user
    #     replicationPasswordKey: replication
